### ISSUE TITLE
not enough bob

### ISSUE THREAD

**Issue by haleyej** [irenayli/bob#1]
basically title, very disappointed by the lack of information about FDIC official Bradley "Bob" O'Brien

**Comment by irenayli** [comment]
is this better

**Comment by irenayli** [comment]
please respond. I seek your feedback urgently

**Comment by haleyej** [comment]
still needs more bob

**Comment by irenayli** [comment]
when he sends me his resume i will add more bob

**Comment by haleyej** [comment]
reopen this you coward

**Comment by irenayli** [comment]
resume section added. please advise
